macshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django_registration.backends.one_step.views import RegistrationView
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth import views as auth_views

from app.views import Index, ProfileView, ProductsView, ProductDetailView, FilterMacBookView, ReviewsView, HelpView, \
    ContactsView, SimpleBuyView, ConfirmView, AddToCartView, CartItemRemoveView, OrderingView, PurchaseHistoryView
from app.forms import CustomUserForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view()),
    path('accounts/register/', RegistrationView.as_view(success_url='/', form_class=CustomUserForm),
         name='django_registration_register'),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
         name='password_change'),
    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('products/<int:pk>', ProductsView.as_view(), name='products'),
    path('product_detail/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('filter/', FilterMacBookView.as_view(), name='filter'),
    path('help/', HelpView.as_view(), name='help'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('reviews/', ReviewsView.as_view(), name='reviews'),
    path('simple_buy/<int:pk>', SimpleBuyView.as_view(), name='simple_buy'),
    path('confirm/', ConfirmView.as_view(), name='confirm'),
    path('add_to_cart/<int:pk>', AddToCartView.as_view(), name='add_to_cart'),
    path('remove_item', CartItemRemoveView.as_view(), name='remove_item'),
    path('ordering', OrderingView.as_view(), name='ordering'),
    path('purchase_history', PurchaseHistoryView.as_view(), name='purchase_history'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.models import ContentType


class CustomUser(AbstractUser):
    """Пользователь"""
    region = models.CharField("Область", max_length=127, null=True)
    city = models.CharField("Город", max_length=127, null=True)
    address = models.CharField("Адрес доставки", max_length=127, null=True)
    phone_number = models.CharField("Мобильный телефон", max_length=12, null=True)
    post_office_number = models.IntegerField("Номер почтового отделения", null=True)


class CreatedAt(models.Model):
    """"Дата создания"""
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Category(models.Model):
    """Модель(тип) MacBook'a"""
    MODEL_AIR = 1
    MODEL_PRO = 2

    MODEL_CHOICES = (
        (MODEL_AIR, 'MacBook Air'),
        (MODEL_PRO, 'MacBook Pro'),
    )
    model = models.PositiveSmallIntegerField("Модель MacBook'a", choices=MODEL_CHOICES, null=True)
    short_description = models.CharField("Краткое описание", max_length=355)
    image = models.ImageField("Изображение", upload_to="categories/")
    max_cpu = models.CharField("Максимальный процессор", max_length=255, null=True,
                               help_text='Введите максимально возможный процессор'
                                         ' для этой модели MacBook')
    max_ram = models.PositiveIntegerField("Максимальный объем оперативной памяти", default=8,
                                          help_text='Введите максимально возможный объем оперативной памяти'
                                                    ' для этой модели MacBook')
    max_hdd = models.CharField("Максимальный объем жесткого диска", default=0, max_length=63,
                               help_text='Введите максимально возможный объем жесткого диска'
                                         ' для этой модели MacBook с указанием единиц измерения')
    max_ssd = models.CharField("Максимальный объем SSD", default=0, max_length=63,
                               help_text='Введите максимально возможный объем SSD'
                                         ' для этой модели MacBook с указанием единиц измерения')
    display = models.PositiveIntegerField("Диагональ экрана", default=13)

    def __str__(self):
        return str(f'{self.get_model_display()} {self.display}')

    class Meta:
        verbose_name = "Модель MacBook'a"
        verbose_name_plural = "Модель MacBook'a"


class Tag(models.Model):
    """Теги"""
    tag = models.CharField("Теги", max_length=255)

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name = "Теги"
        verbose_name_plural = "Теги"


class MacBook(CreatedAt):
    """"MacBook"""
    CONDITION_NEW = 1
    CONDITION_GREAT = 2
    CONDITION_GOOD = 3
    CONDITION_NORMAL = 4
    CONDITION_BAD = 5

    CONDITION_CHOICES = (
        (CONDITION_NEW, "Новый"),
        (CONDITION_GREAT, "Отличное"),
        (CONDITION_GOOD, "Хорошее"),
        (CONDITION_NORMAL, "Нормальное"),
        (CONDITION_BAD, "Плохое"),
    )
    name = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField("Описание", max_length=1023)
    price = models.PositiveIntegerField("Цена", null=True)
    ram = models.PositiveIntegerField("Объем оперативной памяти", default=8)
    hdd = models.CharField("Объем жесткого диска", default=0, max_length=63,
                           help_text='Введите объем с указанием единиц измерения')
    ssd = models.CharField("Объем SSD", default=0, max_length=63,
                           help_text='Введите объем с указанием единиц измерения')
    battery_life = models.PositiveIntegerField("Количество циклов зарядки", default=0)
    display = models.PositiveIntegerField("Диагональ экрана", default=13)
    cpu = models.CharField("Процессор", max_length=255, null=True)
    gpu = models.CharField("Видеокарта", max_length=255, null=True)
    os = models.CharField("Версия ОС", max_length=255, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    complete_set = models.CharField("Комплектация", max_length=255, null=True)
    condition = models.PositiveSmallIntegerField("Состояние", choices=CONDITION_CHOICES, default=None)
    year = models.PositiveIntegerField("Год выпуска", default=2020)
    colour = models.CharField("Цвет", max_length=63, default="Серый", null=True)
    availability = models.BooleanField("Наличие товара", default=False)

    def __str__(self):
        return f'{str(self.name)} {self.year}'


class MacBookImage(models.Model):
    """Картинки MacBook`ов"""
    image = models.ImageField("Изображение", upload_to="macbook_images/")
    macbook = models.ForeignKey(MacBook, verbose_name="Выберите для какого MacBook это фото", on_delete=models.CASCADE,
                                help_text='Выберите для какого MacBook это фото')

    def __str__(self):
        return f'{str(self.macbook)} image'

    class Meta:
        verbose_name = "Фото MacBook"
        verbose_name_plural = "Фото MacBook"


class OneClickPurchaseRequisitions(CreatedAt):
    """Номер телефона покупателя через покупу в один клик"""
    phone_number = models.CharField("Мобильный телефон", max_length=12, null=True)
    product = models.ForeignKey(MacBook, verbose_name="Желаемый ноутбук", on_delete=models.CASCADE)
    processed = models.BooleanField("Обработано", default=False)

    def __str__(self):
        return f'Заявка на покупку №{self.id}'

    class Meta:
        verbose_name = "Заявки на покупку в один клик"
        verbose_name_plural = "Заявки на покупку в один клик"


class Cart(models.Model):
    """Корзина"""

    user = models.ForeignKey(CustomUser, verbose_name='Покупатель', on_delete=models.CASCADE)
    product = models.ForeignKey(MacBook, verbose_name='Продукт', on_delete=models.CASCADE)
    processed = models.BooleanField("Обработано", default=False)

    def __str__(self):
        return f'{self.product.name} id {self.product.id} из корзины'

    class Meta:
        verbose_name = "Товар в корзине"
        verbose_name_plural = "Товар в корзине"


class Order(CreatedAt):
    """Готовый заказ"""

    MAIL_DELIVERY = 1
    COURIER_DELIVERY = 2

    DELIVERY_METHOD_CHOICE = (
        (MAIL_DELIVERY, "Доставка почтой"),
        (COURIER_DELIVERY, "Доставка курьером"),
    )

    user = models.ForeignKey(CustomUser, verbose_name='Покупатель', on_delete=models.CASCADE)
    products = models.ManyToManyField(Cart, verbose_name='Продукты', default=None)
    delivery_method = models.PositiveSmallIntegerField("Способ доставки", choices=DELIVERY_METHOD_CHOICE, default=1)
    final_price = models.FloatField("Цена")
    first_name = models.CharField("Имя", max_length=127, null=True)
    last_name = models.CharField("Фамилия", max_length=127, null=True)
    region = models.CharField("Область", max_length=127, null=True)
    city = models.CharField("Город", max_length=127, null=True)
    address = models.CharField("Адрес доставки", max_length=127, null=True, blank=True)
    phone_number = models.CharField("Мобильный телефон", max_length=12, null=True)
    post_office_number = models.IntegerField("Номер почтового отделения", null=True, blank=True)
    in_order = models.BooleanField('Оброботано', default=False)

    def __str__(self):
        return f'Заказ № {self.id}'

    class Meta:
        verbose_name = "Заказы"
        verbose_name_plural = "Заказы"


class Reviews(CreatedAt):
    """Отзывы"""

    username = models.ForeignKey(CustomUser, verbose_name='Покупатель', on_delete=models.CASCADE)
    text = models.CharField("Комментарий", max_length=512)
    rating_star = models.SmallIntegerField("Звезды", default=0)

    def __str__(self):
        return f'Отзыв пользователя {self.username}'

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

templates/purchase/confirmed.html
{% extends 'navbar.html' %}
{% load bootstrap4 static %}

{% block header %}
    <title>Заявка подтверждена!</title>
    <link rel="stylesheet" href="{% static 'css/confirmed-style.css' %}">
{% endblock %}
{% block navbar %}
    <div class="border">
        <h2>Ваша заявка подтверждена! Ожидайте звонка оператора.</h2>
        <h3>Спасибо за ваш заказ!</h3>
    </div>
{% endblock %}

templates/purchase/ordering.html
{% extends 'navbar.html' %}
{% load bootstrap4 static %}

{% block header %}
    <title>Оформить заказ</title>
{% endblock %}
{% block navbar %}
    <div class="row" style="margin-top: 40px">
        <div class="col-4">
            <h2 class="text-center">Ваш заказ</h2>
            <div class="dropdown-divider"></div>
            <div class="cart-scroll" style="height: 650px">
                {% for products in cart %}
                    <div class="card border-off" style="margin-bottom: -5px">
                        <div class="row no-gutters">
                            <div class="col-md-4">
                                <img src="{{ products.product.macbookimage_set.all.0.image.url }}"
                                     class="card-img" alt="...">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body b">
                                    <h5 class="card-title">{{ products.product.name }}</h5>
                                    <p class="card-text">Экран: {{ products.product.display }} /
                                        {{ products.product.cpu }}/
                                        {{ products.product.ram }} ГБ /
                                        SSD: {{ products.product.ssd }} /
                                        HDD: {{ products.product.hdd }} /
                                        Циклов зарядки батареи: {{ products.product.battery_life }} /
                                        Состояние: {{ products.product.get_condition_display }}</p>
                                    <h4 style="text-align: end">Цена: {{ products.product.price }} $</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="dropdown-divider"></div>
                {% endfor %}
            </div>
            <h3 style="text-align: end; padding: 15px">К оплате: {{ final_price }} $</h3>
        </div>
        <div class="col-8">
            <div class="container">
                <h2 class="text-center">Личные данные</h2>
                <form method="post" class="form" enctype="multipart/form-data">{% csrf_token %}
                    {% bootstrap_form form %}

                    <button type="submit" class="btn btn-light">Подтвердить заказ</button>
                </form>
            </div>
        </div>
{% endblock %}

templates/purchase/simple_buy.html
{% extends 'navbar.html' %}
{% load bootstrap4 static %}

{% block header %}
    <title>Купить в один клик</title>
{% endblock %}
{% block navbar %}
    <div class="row" style="margin-top: 20px">
        <div class="col-6">
            <h2 class="text-center">Вами была выбраная следующая модель MacBook: </h2>
            <div class="card" style="width: 30rem;">
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        {% for image in mac.macbookimage_set.all %}
                            {% if image == mac.macbookimage_set.all.0 %}
                                <div class="carousel-item active">
                                    <img src="{{ image.image.url }}" class="card-img-top" alt="...">
                                </div>
                            {% else %}
                                <div class="carousel-item">
                                    <img src="{{ image.image.url }}" class="card-img-top" alt="...">
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button"
                       data-slide="prev" style="color: black; font-size: 20px">
                        <
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button"
                       data-slide="next" style="color: black; font-size: 20px">
                        >
                    </a>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ mac.name }} {{ mac.year }}</h5>
                    <p class="card-text">Экран: {{ mac.display }} / {{ mac.cpu }} / {{ mac.ram }} ГБ /
                        SSD: {{ mac.ssd }} / HDD: {{ mac.hdd }} / Циклов зарядки
                        батареи: {{ mac.battery_life }} /
                        Состояние: {{ mac.get_condition_display }}</p>
                    <p class="card-text">
                    <h3>{{ mac.price }} $</h3>Добавлено:<br>{{ mac.created_at }} </p>
                </div>
            </div>
        </div>
        <div class="col-6 text-center">
            <h2>Для дальнейшего оформления вашего заказа укажите ваш номер телефона</h2>
            <form method="post">{% csrf_token %}
                <table class="text-center">
                    {% bootstrap_form form %}
                    <div style="display: flex; justify-content: flex-end;">
                        <button type="submit" class="btn btn-light" style="margin: 10px;">Подтвердить заявку</button>
                    </div>
                </table>
            </form>
            <p>Наши операторы свяжутся с вами в ближайшее время</p>
        </div>
    </div>

{% endblock %}